export {default as Hero} from "./Hero"
export {default as About} from "./About"
export {default as Blog} from "./Blog"
export {default as CardSect} from "./CardSect"
export {default as Forum} from "./Forum"
export {default as Possibilty} from "./Possiblity"
export {default as Spons} from "./Spons"
